/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package games.ttt.view;

/**
 *
 * @author Asus
 */
public class TttBoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form TttBoardPanel
     */
    public TttBoardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tttBoardModel2 = new games.ttt.model.TttBoardModel();

        setMaximumSize(new java.awt.Dimension(450, 450));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(450, 450));
        setLayout(new java.awt.GridBagLayout());

        tttBoardModel2.setFontTitle(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        tttBoardModel2.setMaximumSize(new java.awt.Dimension(450, 450));
        tttBoardModel2.setMinimumSize(new java.awt.Dimension(450, 450));
        tttBoardModel2.setPreferredSize(new java.awt.Dimension(450, 450));
        add(tttBoardModel2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private games.ttt.model.TttBoardModel tttBoardModel2;
    // End of variables declaration//GEN-END:variables
}
